#!/usr/bin/env python
import getopt
import pathlib
import re
import struct
import sys

FIGURE_RE = re.compile(r"""
    ^(?P<ws>\s*)
    {{
       figure:
       \s*
       "(?P<name>[^"]+)"
       \s*
       (
          file:
          (?P<filename>[^}]+)
       )?
       \s*
    }}$""", re.VERBOSE)

def count(filename, indir, missing):
    figcount = 0
    midicount = 0
    lineno = 0
    infile = open(filename)
    for line in infile:
        lineno += 1
        line = line.rstrip()
        m = FIGURE_RE.match(line)
        if not m:
            continue
        fullname = m.group('name')
        figname = m.group('filename')
        if not figname:
            figname = fullname.lower().replace(" ", "")
        figcount += 1
        midifile = pathlib.Path(f"{indir}/{figname}.midi")
        if midifile.is_file():
            midicount += 1
        elif missing:
            print(f"    {figname} not found")
    return (midicount, figcount)

def usage():
    print("count [options] infile.html [infile2.html ...]")
    print("  -d <dir> / --dir <dir>      : directory holding images (default \"docs\")")
    print("  -v / --verbose              : show detailed output")
    print("  -f / --files e              : show missing files")

def main(args):
    indir = "docs"
    verbose = False
    missing = False
    try:
        opts, args = getopt.getopt(args, "hd:vf", ["help", "dir=", "verbose", "files"])
    except getopt.GetoptError as err:
        print(err)  # will print something like "option -a not recognized"
        usage()
        sys.exit(2)
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o in ("-d", "--dir"):
            indir = a
        elif o in ("-v", "--verbose"):
            verbose = True
        elif o in ("-f", "--files"):
            missing = True
        else:
            assert False, "unhandled option"

    figcount = 0
    midicount = 0
    for arg in args:
        (m, n) = count(arg, indir, missing)
        midicount += m
        figcount += n
        if (verbose or n != m) and n != 0:
            print(f"  {arg}: done {m} of {n} ({m/n:.1%}), {n-m} to do")
    print(f"Done {midicount} of {figcount} ({midicount/figcount:.1%}), {figcount - midicount} to do")

if __name__ == "__main__":
    main(sys.argv[1:])
